/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 HelloWorld.gltf --transform
Author: omri_ha_muglob (https://sketchfab.com/omri_ha_muglob)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hello-world-in-python-d03131b79986432d80e7ad6751abe880
Title: "Hello, World!" in Python
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/HelloWorld-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.text} />
      </group>
    </group>
  )
}

useGLTF.preload('/HelloWorld-transformed.glb')
